### ISSUE TITLE
cf:ifelse-value can't handle conditionals with prefix predicates

### ISSUE THREAD

**Issue by qiemem** [qiemem/ControlFlowExtension#9]
For instance, it errors on:

```
(cf:ifelse-value
  false [ 0 ]
  any? turtles [ 1 ]
  any? patches [ 2 ]
  [ 3 ])
```

The problem is that the `any?` gets eaten as an anonymous reporter.

**Comment by mrerrormessage** [comment]
Is this a deal-breaker, or merely an inconvenience?

**Comment by qiemem** [comment]
Just an inconvenience.

The workaround for this is just to throw parens around the conditionals:

```
(cf:ifelse-value
  false [ 0 ]
  (any? turtles) [ 1 ]
  (any? patches) [ 2 ]
  [ 3 ])
```

Also, a plausible fix that would not require a dramatic reworking of the compiler would be to have a way for `[ 1 ]` to be interpreted as an anonymous reporter but not `any?`. Maybe something like making it so that *only* `Syntax.ReporterType` or `Syntax.CommandType` will convert a named procedure to a lambda (but still have any use of those, except when `|`ed with `Syntax.ListType` or `Syntax.BlockType`, infer the `->` in a block).

**Comment by mrerrormessage** [comment]
Good to know it's not a showstopper.

> Also, a plausible fix that would not require a dramatic reworking of the compiler would be to have a way for [ 1 ] to be interpreted as an anonymous reporter but not `any?`.

I don't know whether this is possible without a fairly substantial compiler change, actually. In order to allow concise reporters (eg. `map ["a" "ab" "abc"] length`) the expression parser assumes that a lone reporter in the position where an anonymous reporter is expected is supposed to be transformed into an anonymous reporter. There are a few ways this could potentially be resolved:

* Define a new syntax type for an anonymous reporter which cannot be concise and adapt ExpressionParser accordingly.
* And/or extend syntax types so that a primitive can represent more precisely what kinds of anonymous procedures it will accept (and adapt ExpressionParser accordingly).

**Comment by qiemem** [comment]
> In order to allow concise reporters (eg. map ["a" "ab" "abc"] length) the expression parser assumes that a lone reporter in the position where an anonymous reporter is expected is supposed to be transformed into an anonymous reporter.

That's why I was hoping that only doing lone reporter expansion in places where *only* a lambda is expected would  do the trick. Regardless, what part of the code is this in? I wouldn't mind tinkering and getting a better understanding of that code.

**Comment by mrerrormessage** [comment]
> That's why I was hoping that only doing lone reporter expansion in places where only a lambda is expected would do the trick.

The only built-in primitives which would break as a result of the suggested change is `run`/`runresult`, since they accept either strings *or* anonymous procedures. I would have to think more about whether autoconversion is feasible.

> Regardless, what part of the code is this in?

The exact code that does this is [here](https://github.com/NetLogo/NetLogo/blob/hexy/parser-core/src/main/parse/ExpressionParser.scala#L413-L415).
